version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - ccamel
    commit-message:
      prefix: "u"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "daily"
    assignees:
      - ccamel
    open-pull-requests-limit: 5
    commit-message:
      prefix: "u"
